services:
  web:
    # Ersetze 'DEIN_DOCKER_USER' mit deinem tats√§chlichen Docker Hub Namen
    build: .
    image: l8tenever/l8tefuel:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/l8tefuel.db
      - SECRET_KEY=supersecretkeychangeit
      - TANKERKOENIG_API_KEY=00000000-0000-0000-0000-000000000002 # Public Example Key
    restart: always
