services:
  web:
    # Ersetze 'DEIN_DOCKER_USER' mit deinem tats√§chlichen Docker Hub Namen
    image: l8tenever/l8tefuel:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./app/data/l8tefuel.db
      - SECRET_KEY=supersecretkeychangeit
    restart: always
